/*
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/networkmachinery/networkmachinery-operators/pkg/apis/networkmachinery/v1alpha1"
	scheme "github.com/networkmachinery/networkmachinery-operators/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// NetworkPerformanceTestsGetter has a method to return a NetworkPerformanceTestInterface.
// A group's client should implement this interface.
type NetworkPerformanceTestsGetter interface {
	NetworkPerformanceTests() NetworkPerformanceTestInterface
}

// NetworkPerformanceTestInterface has methods to work with NetworkPerformanceTest resources.
type NetworkPerformanceTestInterface interface {
	Create(*v1alpha1.NetworkPerformanceTest) (*v1alpha1.NetworkPerformanceTest, error)
	Update(*v1alpha1.NetworkPerformanceTest) (*v1alpha1.NetworkPerformanceTest, error)
	UpdateStatus(*v1alpha1.NetworkPerformanceTest) (*v1alpha1.NetworkPerformanceTest, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.NetworkPerformanceTest, error)
	List(opts v1.ListOptions) (*v1alpha1.NetworkPerformanceTestList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.NetworkPerformanceTest, err error)
	NetworkPerformanceTestExpansion
}

// networkPerformanceTests implements NetworkPerformanceTestInterface
type networkPerformanceTests struct {
	client rest.Interface
}

// newNetworkPerformanceTests returns a NetworkPerformanceTests
func newNetworkPerformanceTests(c *NetworkmachineryV1alpha1Client) *networkPerformanceTests {
	return &networkPerformanceTests{
		client: c.RESTClient(),
	}
}

// Get takes name of the networkPerformanceTest, and returns the corresponding networkPerformanceTest object, and an error if there is any.
func (c *networkPerformanceTests) Get(name string, options v1.GetOptions) (result *v1alpha1.NetworkPerformanceTest, err error) {
	result = &v1alpha1.NetworkPerformanceTest{}
	err = c.client.Get().
		Resource("networkperformancetests").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of NetworkPerformanceTests that match those selectors.
func (c *networkPerformanceTests) List(opts v1.ListOptions) (result *v1alpha1.NetworkPerformanceTestList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.NetworkPerformanceTestList{}
	err = c.client.Get().
		Resource("networkperformancetests").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested networkPerformanceTests.
func (c *networkPerformanceTests) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("networkperformancetests").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a networkPerformanceTest and creates it.  Returns the server's representation of the networkPerformanceTest, and an error, if there is any.
func (c *networkPerformanceTests) Create(networkPerformanceTest *v1alpha1.NetworkPerformanceTest) (result *v1alpha1.NetworkPerformanceTest, err error) {
	result = &v1alpha1.NetworkPerformanceTest{}
	err = c.client.Post().
		Resource("networkperformancetests").
		Body(networkPerformanceTest).
		Do().
		Into(result)
	return
}

// Update takes the representation of a networkPerformanceTest and updates it. Returns the server's representation of the networkPerformanceTest, and an error, if there is any.
func (c *networkPerformanceTests) Update(networkPerformanceTest *v1alpha1.NetworkPerformanceTest) (result *v1alpha1.NetworkPerformanceTest, err error) {
	result = &v1alpha1.NetworkPerformanceTest{}
	err = c.client.Put().
		Resource("networkperformancetests").
		Name(networkPerformanceTest.Name).
		Body(networkPerformanceTest).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *networkPerformanceTests) UpdateStatus(networkPerformanceTest *v1alpha1.NetworkPerformanceTest) (result *v1alpha1.NetworkPerformanceTest, err error) {
	result = &v1alpha1.NetworkPerformanceTest{}
	err = c.client.Put().
		Resource("networkperformancetests").
		Name(networkPerformanceTest.Name).
		SubResource("status").
		Body(networkPerformanceTest).
		Do().
		Into(result)
	return
}

// Delete takes name of the networkPerformanceTest and deletes it. Returns an error if one occurs.
func (c *networkPerformanceTests) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("networkperformancetests").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *networkPerformanceTests) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("networkperformancetests").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched networkPerformanceTest.
func (c *networkPerformanceTests) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.NetworkPerformanceTest, err error) {
	result = &v1alpha1.NetworkPerformanceTest{}
	err = c.client.Patch(pt).
		Resource("networkperformancetests").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
