/*
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/networkmachinery/networkmachinery-operators/pkg/apis/networkmachinery/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeNetworkPerformanceTests implements NetworkPerformanceTestInterface
type FakeNetworkPerformanceTests struct {
	Fake *FakeNetworkmachineryV1alpha1
}

var networkperformancetestsResource = schema.GroupVersionResource{Group: "networkmachinery.io", Version: "v1alpha1", Resource: "networkperformancetests"}

var networkperformancetestsKind = schema.GroupVersionKind{Group: "networkmachinery.io", Version: "v1alpha1", Kind: "NetworkPerformanceTest"}

// Get takes name of the networkPerformanceTest, and returns the corresponding networkPerformanceTest object, and an error if there is any.
func (c *FakeNetworkPerformanceTests) Get(name string, options v1.GetOptions) (result *v1alpha1.NetworkPerformanceTest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(networkperformancetestsResource, name), &v1alpha1.NetworkPerformanceTest{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NetworkPerformanceTest), err
}

// List takes label and field selectors, and returns the list of NetworkPerformanceTests that match those selectors.
func (c *FakeNetworkPerformanceTests) List(opts v1.ListOptions) (result *v1alpha1.NetworkPerformanceTestList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(networkperformancetestsResource, networkperformancetestsKind, opts), &v1alpha1.NetworkPerformanceTestList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.NetworkPerformanceTestList{ListMeta: obj.(*v1alpha1.NetworkPerformanceTestList).ListMeta}
	for _, item := range obj.(*v1alpha1.NetworkPerformanceTestList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested networkPerformanceTests.
func (c *FakeNetworkPerformanceTests) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(networkperformancetestsResource, opts))
}

// Create takes the representation of a networkPerformanceTest and creates it.  Returns the server's representation of the networkPerformanceTest, and an error, if there is any.
func (c *FakeNetworkPerformanceTests) Create(networkPerformanceTest *v1alpha1.NetworkPerformanceTest) (result *v1alpha1.NetworkPerformanceTest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(networkperformancetestsResource, networkPerformanceTest), &v1alpha1.NetworkPerformanceTest{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NetworkPerformanceTest), err
}

// Update takes the representation of a networkPerformanceTest and updates it. Returns the server's representation of the networkPerformanceTest, and an error, if there is any.
func (c *FakeNetworkPerformanceTests) Update(networkPerformanceTest *v1alpha1.NetworkPerformanceTest) (result *v1alpha1.NetworkPerformanceTest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(networkperformancetestsResource, networkPerformanceTest), &v1alpha1.NetworkPerformanceTest{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NetworkPerformanceTest), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeNetworkPerformanceTests) UpdateStatus(networkPerformanceTest *v1alpha1.NetworkPerformanceTest) (*v1alpha1.NetworkPerformanceTest, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(networkperformancetestsResource, "status", networkPerformanceTest), &v1alpha1.NetworkPerformanceTest{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NetworkPerformanceTest), err
}

// Delete takes name of the networkPerformanceTest and deletes it. Returns an error if one occurs.
func (c *FakeNetworkPerformanceTests) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(networkperformancetestsResource, name), &v1alpha1.NetworkPerformanceTest{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNetworkPerformanceTests) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(networkperformancetestsResource, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.NetworkPerformanceTestList{})
	return err
}

// Patch applies the patch and returns the patched networkPerformanceTest.
func (c *FakeNetworkPerformanceTests) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.NetworkPerformanceTest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(networkperformancetestsResource, name, pt, data, subresources...), &v1alpha1.NetworkPerformanceTest{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NetworkPerformanceTest), err
}
